### ISSUE TITLE
assert error when enabled=false

### ISSUE THREAD

**Issue by gskinner** [jonahwilliams/flutter_shaders#12]
`assert(offset == Offset.zero)` in `_RenderShaderSamplerBuilderWidget.paint` throws when `enabled=false`.

**Comment by gskinner** [comment]
I fixed this by checking enabled at the top of `_RenderShaderSamplerBuilderWidget.paint`:

```
  void paint(PaintingContext context, Offset offset) {
    if (size.isEmpty || !_enabled) {
      return;
    }
// etc
```

Happy to submit a PR for this @jonahwilliams

**Comment by jonahwilliams** [comment]
Ahh, good catch. Happy to review a PR
