### ISSUE TITLE
How to convert shaderToy shaders to Flutter Interpretable shaders

### ISSUE THREAD

**Issue by jhonatan-3a** [jonahwilliams/flutter_shaders#13]
Im basically new to this shader thing and i would like to should some shaderToy shaders with flutter, after many attempts of looking at repos and trying to translate what the shadertoy code is to something flutter can understand, im still stuck and i find no guidelines on what funciones or code is avaialable for flutter to interpret, any help would be greatly appreciated

**Comment by jonahwilliams** [comment]
You'll probably want to start here: https://docs.flutter.dev/development/ui/advanced/shaders

If you have specific questions that are lacking in the documentation, you should open issues on the main flutter repository.
