### ISSUE TITLE
_ShaderSamplerBuilderLayer throws "Invalid image dimensions" if target has no size.

### ISSUE THREAD

**Issue by gskinner** [jonahwilliams/flutter_shaders#14]
`_ShaderSamplerBuilderLayer._buildChildScene` throws an "Invalid image dimensions" error if the target widget does not have a size, which is difficult to resolve in a number of scenarios.

I resolved this by checking the size at the top of `_ShaderSamplerBuilderLayer.addToScene`:

```
void addToScene(ui.SceneBuilder builder) {
    if (size.isEmpty) return;
// etc
```

Happy to submit a PR for this @jonahwilliams

**Comment by jonahwilliams** [comment]
Also good catch :)

**Comment by gskinner** [comment]
Want me to just package these as a single PR?

**Comment by jonahwilliams** [comment]
sure!
