### ISSUE TITLE
AnimatedSampler Exhibits Poor Performance on Web

### ISSUE THREAD

**Issue by jonaird** [jonahwilliams/flutter_shaders#19]
I am having significant performance issues on Web that I think have to do with [this issue](https://github.com/flutter/flutter/issues/117786) regarding the performance of `toImage` in the Flutter framework on CanvasKit. Unfortunately the issue is locked. I can't comment on it and I didn't want to duplicate it. For reference, when using `AnimatedSampler` the `toImageSync` call is taking more than 70 milliseconds in release mode while my shader is active making shaders completely unusable for my use case.

Is there a workaround for this?

**Comment by jonahwilliams** [comment]
Yes, that is the correct issue. unfortunately there is no workaround. I would not recommend using AnimatedSampler on the web.

**Comment by jonaird** [comment]
For anyone else facing this issue ` --dart-define=BROWSER_IMAGE_DECODING_ENABLED=false` seems to improve things.  Also the `toImageSync` call time is directly proportional to the size of the widget being converted to an image so smaller widgets work ok. Combining these together I'm able to get 30+ fps.

**Comment by GentleTechTeam** [comment]
@jonaird sorry, maybe i found the solution? How to use image samplers with web?

**Comment by Spiritcow** [comment]
@jonaird Hi, maybe you found the solution how to use samplers with shaders on the web? Without lag?
