### ISSUE TITLE
Memory leaks on Android

### ISSUE THREAD

**Issue by feduke-nukem** [jonahwilliams/flutter_shaders#21]
Similar to https://github.com/jonahwilliams/flutter_shaders/issues/17.

I have good performance on the iOS Simulator and iPhone 7 (physical device).

However, profiling both the Huawei Mate 20 lite and the default Pixel 6 API 33 emulator (ARM) is leading to memory leaks.
I assume that this is happening due to frequent rebuilds and the use of `scene.toImageSync`. [Link](https://github.com/feduke-nukem/animated_glitch/blob/911774436e25abba129b59541c90550b7421260e/lib/src/widget/animated_glitch_with_shader.dart)

https://github.com/jonahwilliams/flutter_shaders/assets/72284940/181a8b16-a907-446a-b475-8f3210e2b797

https://github.com/jonahwilliams/flutter_shaders/assets/72284940/7d16b50f-faaa-4330-919e-86f73bb8ba32

https://github.com/jonahwilliams/flutter_shaders/assets/72284940/a0ebb9df-772b-43b4-b968-d43a3365f33c

However, if I use a raw ui.Image with CustomPaint, which is not desired because it won't reflect the provided widget changes, the performance is fine since there are no frequent `imageSync calls`. [Link](https://github.com/feduke-nukem/animated_glitch/blob/shader/lib/src/widget/animated_glitch_with_shader.dart)

Do you have any ideas on how to prevent such behavior?

**Comment by jonahwilliams** [comment]
You could try the branch at https://github.com/jonahwilliams/flutter_shaders/pull/20 to see if that helps. I haven't had the time this week to dig in much deeper, but you're not the only one to report this issue

**Comment by feduke-nukem** [comment]
> You could try the branch at #20 to see if that helps. I haven't had the time this week to dig in much deeper, but you're not the only one to report this issue

I have tried, but it didn't help.

**Comment by jonahwilliams** [comment]
Good to know. FWIW while I'll land the PR I linked sometime this next week I don't plan to work on this further as I'm busy at work. If you investigate further and find a way to fix this I'm happy to accept the contribution.

**Comment by jonahwilliams** [comment]
I'm going to need more details on how to reproduce this. With the basic sample in the repo, I'm unable to reproduce any significant memory leakage. @feduke-nukem if you're able to narrow this down to a smaller reproduction that would be helpful.

From what I can see locally, nothing in the AnimatedSampler is retaining the ui.Image or ui.Picture, so beyond a bug in dart:ui itself I don't know what it could be.

**Comment by feduke-nukem** [comment]
> I'm going to need more details on how to reproduce this. With the basic sample in the repo, I'm unable to reproduce any significant memory leakage. @feduke-nukem if you're able to narrow this down to a smaller reproduction that would be helpful.
> 
> From what I can see locally, nothing in the AnimatedSampler is retaining the ui.Image or ui.Picture, so beyond a bug in dart:ui itself I don't know what it could be.

Okay, I will do it later

**Comment by feduke-nukem** [comment]
> I'm going to need more details on how to reproduce this. With the basic sample in the repo, I'm unable to reproduce any significant memory leakage. @feduke-nukem if you're able to narrow this down to a smaller reproduction that would be helpful.
> 
> From what I can see locally, nothing in the AnimatedSampler is retaining the ui.Image or ui.Picture, so beyond a bug in dart:ui itself I don't know what it could be.

Here's [repo](https://github.com/feduke-nukem/flutter_shaders_memory_leak_example)

I am testing on physical Android Huawei Mate 20 lite and Emulator (default Pixel 33 API) 
<img width="507" alt="image" src="https://github.com/jonahwilliams/flutter_shaders/assets/72284940/4edafdc6-0a58-4ce1-b4d4-d2f78d621238">


Also, I've noticed that the [scene object used to produce the picture](https://github.com/jonahwilliams/flutter_shaders/blob/be68f3470a1c2452662d80910955dccb29c89f7b/lib/src/animated_sampler.dart#L229C39-L229C39) isn't disposed, but it doesn't help either (I've checked that).

**Comment by jonahwilliams** [comment]
Thanks, I will take a look this week!

**Comment by jonahwilliams** [comment]
I can run this sample locally on a Pixel 6 and confirm that both the Dart image object and the native image wrapper are disposed, and there is no gradual memory increase in either the Dart or native heap.

**Comment by jonahwilliams** [comment]
(I'll try on an emulator later)

**Comment by jonahwilliams** [comment]
What I suspect you may be seeing is that the native resources are only disposed at a minimum every n MS (where N is some fairly large number like 30 or 40). This may be more pronounced on an emulator because its not a real GPU backend and must do more expensive emulation.

**Comment by feduke-nukem** [comment]
> What I suspect you may be seeing is that the native resources are only disposed at a minimum every n MS (where N is some fairly large number like 30 or 40). This may be more pronounced on an emulator because its not a real GPU backend and must do more expensive emulation.

The problem is that this issue also occurs on a real device. The very first video in this conversation demonstrates a drop in FPS, and after some time, the application freezes and crashes (similar to the system killing the process).

It works just fine on iOS physical devices (iPhone 7 e.g. 60 fps stable) and some other Androids.

**Comment by feduke-nukem** [comment]
> What I suspect you may be seeing is that the native resources are only disposed at a minimum every n MS (where N is some fairly large number like 30 or 40). This may be more pronounced on an emulator because its not a real GPU backend and must do more expensive emulation.

I assume that my phone is an old, outdated device, and maybe this is the real problem, idk.

**Comment by jonahwilliams** [comment]
It doesn't really make any sense that the behavior you're observing varies by manufacturer though. its not like the flutter engine works differently on older phones.

**Comment by feduke-nukem** [comment]
> It doesn't really make any sense that the behavior you're observing varies by manufacturer though. its not like the flutter engine works differently on older phones.

By "old," I mean that it is simply a performance-related issue. My Android device experiences a default drop in FPS whenever there are animations, but in this case, it is critical.

Well, that's weird anyway.

**Comment by feduke-nukem** [comment]
@jonahwilliams I tried replacing the approach of creating an image for a shader from the 'Scene' to using 'RepaintBoundary,' and I can confirm that the problem is gone when I use the `toImage` method instead of `toImageSync`. 
I don't have a real understanding of why, but it works. Maybe this information will be helpful somehow.

**Comment by andreasmpet** [comment]
It's clear that this is a bug in flutter. The flutter team seems to be on the case now at least :) We'll just have to wait patiently until they fix it.
