### ISSUE TITLE
Unexpected Null Safety Error with AnimatedSampler

### ISSUE THREAD

**Issue by ghost** [jonahwilliams/flutter_shaders#22]
I am using the AnimatedSampler class from the flutter_shaders package in my Flutter application. I am running into an unexpected issue with Dart's null safety.

The AnimatedSampler requires a non-nullable Widget child. I provide a Widget as required, however, I receive a linter warning indicating that the child could be null. My assumption is that this is related to the asynchronous nature of widget building in Flutter, where the child may not be fully built at the moment it's required by AnimatedSampler.

To bypass the warning, I tried to use the null check operator (!). The AnimatedSampler does not seem to accept this workaround, and I receive an error at runtime: "The argument type 'Widget?' can't be assigned to the parameter type 'Widget'".

Code to reproduce the issue:

```
class ShaderSampler extends StatelessWidget {
  const ShaderSampler({
    Key? key,
    required this.child,
    required this.value,
  }) : super(key: key);

  final Widget child;
  final double value;

  @override
  Widget build(BuildContext context) {
    print("ShaderSampler's child: $child");
    return ShaderBuilder(
      (context, shader, child) {
        return AnimatedSampler(
          (image, size, canvas) {
            shader.setFloat(0, value);
            shader.setFloat(1, value);
            shader.setFloat(2, size.width);
            shader.setFloat(3, size.height);
            shader.setImageSampler(0, image);

            canvas.drawRect(
              Rect.fromLTWH(0, 0, size.width, size.height),
              Paint()..shader = shader,
            );
          },
          child: const SingleColumnLayout(),
        );
      },
      assetKey: 'assets/shaders/pixelation.frag',
    );
  }
}
```

Error message:
"The argument type 'Widget?' can't be assigned to the parameter type 'Widget'"

Could you please provide some guidance or clarification about this issue? Is this a bug, a design issue with AnimatedSampler, or an unusual interaction between Flutter's widget building and Dart's null safety?

Thanks for your help.
![Example passing widget](https://github.com/jonahwilliams/flutter_shaders/assets/44120439/1f885c6f-f88e-4748-b6d6-0b11137bca24)
![exception using null operator](https://github.com/jonahwilliams/flutter_shaders/assets/44120439/b7d7d65f-f4b5-4990-8603-267de9529bdf)

**Comment by jonahwilliams** [comment]
The issue tracker is for bugs related to the flutter_samplers package, it is not a venue for asking for help with your code.

(In your example `child` is the parameter from the ShaderBuilder and not your widget parameter, you've shadowed it)
