### ISSUE TITLE
Pixelation Shader not working with Backdrop filter.

### ISSUE THREAD

**Issue by immi420** [jonahwilliams/flutter_shaders#26]
I want this type of effect in Flutter and it seems the **Pixelation shader** will work.
but using it with BackdropFilter Nothing Happens.
Do you have any guide to use it with BackdropFilter?

Reference Image:
Instagram Profile View

![F1vPIa6aAAA26wb](https://github.com/jonahwilliams/flutter_shaders/assets/30823817/aa23edaf-d9ba-4b4c-9b3d-c1d3253af1bd)

**Comment by jonahwilliams** [comment]
Its currently not possible with the APIs exposed in the flutter framework. We'd need the ability to generate an ImageFilter from a user authored fragment program.

That would actually more or less eliminate the need for this package :)

I've been thinking about this for a while, I'll file a bug with my thoughts on flutter/flutter and link that here.

**Comment by immi420** [comment]
Thanks, i hope it'll come up in the next Updates.

**Comment by jonahwilliams** [comment]
Support for this was added to the engine, but you need to use the new ImageFilter.shader and not this package.
