### ISSUE TITLE
Package not working for Web iOS/iPadOS Safari?

### ISSUE THREAD

**Issue by LenWdk** [jonahwilliams/flutter_shaders#27]
Hello there. I'm having fun implementing shaders and want to thank you for your work on this package. I've been using it on iOS, macOS, and the web. However, when using Safari or another browser on iPhones/iPads, my shaders don't render. Is this a known limitation, or am I doing something wrong?

**Comment by LenWdk** [comment]
I found out that the same issue occurs on (older?) Android web browsers. I'm puzzled because using Three.js I was able to render the shaders on those devices.

**Comment by jonahwilliams** [comment]
Its possible you were using the HTML renderer. The fragment program API only works on CanvasKit.

**Comment by LenWdk** [comment]
Hello, thanks for the response. I was not using the html renderer. In fact, I get the same result using this [official flutter sample](https://github.com/flutter/samples/tree/main/simple_shader). I'll open an issue on the flutter repository. Thanks for your time.

**Comment by LenWdk** [comment]
I forgot about `--web-renderer  auto` and was using the HTML renderer on mobile. You were right. Thank's again

**Comment by jonahwilliams** [comment]
No problem
