### ISSUE TITLE
Possibility of using persistent buffer with AnimatedSampler

### ISSUE THREAD

**Issue by justyn** [jonahwilliams/flutter_shaders#28]
Hi

Thanks very much for this library. I've been using `AnimatedSampler` to create some shader effects over a widget, using examples from [shadertoy](shadertoy.com) as a reference/inspiration.

One thing I cannot work out how to do is create fading trails or anything like that, because data generated in the previous frame's render isn't available to the next.

See [this shadertoy example in which you can click and create a trail with the mouse](https://www.shadertoy.com/view/WlsGRM). This is achieved in less than 10 lines of code.

I've never used shaders before, but I think it manges this by doing two passes (seen in the tabs on the shadertoy page): 
* Buffer A
* Image

Where "Buffer A" is somehow persistent and used by "Image".

Is this possible to do using AnimatedSampler (or even possible at all in Flutter?)

Thank you.

**Comment by jonahwilliams** [comment]
Its not a goal of this library to make it easy to create shader playgrounds, just to apply shaders to existing widget trees.

You can do what you want today, but you'd need to manage the canvas operations yourself. For example:

```
import 'dart:ui' as ui;

// frame 1
var recorder = ui.PictureRecorder();
var canvas = ui.Canvas(recorder); 
canvas.drawRect(..., Paint()..shader = /* your shader */)
var picture = recorder.endRecording();

// Now feed this image in as input to frame 2, et cetera.
var image = picture.toImageSync();


```

**Comment by justyn** [comment]
I see, thanks for the example
