### ISSUE TITLE
AnimatedSampler issue

### ISSUE THREAD

**Issue by davidd647** [jonahwilliams/flutter_shaders#29]
Please let me start off by saying: wow! Amazing tool!

I can do most of what I'd like, but taking the (fully working! wow!) AnimatedSampler pixelation example, and I try to add another uniform, it crashes with `RangeError (index): Index out of range: index should be less than n: n`. This happens fairly often with a number of different changes to my .frag code (even if it doesn't relate to how many uniforms I expect in the .frag code).

This happens whether I use shader.setFloatUniforms, or if I set uniforms individually... Part of me suspects this error is on the end of the Flutter team, who I also love.

I've attached screen caps of the error that I can least understand. I think it's related to the issue above, since it's still an `Index out of range` error (only lines 22, 23, 24, and 26 are commented out - everything else is the same).

Is this a common issue? Please let me know if more information would be helpful.
![Screenshot 2023-10-20 at 2 23 45 AM](https://github.com/jonahwilliams/flutter_shaders/assets/17207891/89b7c706-72d7-42e4-8edf-e1cc577ab7e3)
![Screenshot 2023-10-20 at 2 24 51 AM](https://github.com/jonahwilliams/flutter_shaders/assets/17207891/835f3aa2-fd9f-4135-9445-5d368042f92e)

Trying to make metaballs based on circular containers with a radial gradient... 🤔

**Comment by jonahwilliams** [comment]
First of all, please don't ever file bugs with screenshots of code. Just put the code in the issue so it can be searched/copied.

Your problem is that the `uSize` uniform is unused, so it is being optimized out. See https://github.com/flutter/flutter/issues/116900

**Comment by davidd647** [comment]
The way I read that felt a bit negative, but that was very helpful... Might just be my tendency of how to read tones. 🤷‍♂️

Do you have anything like a Patreon for people like me to show support?

**Comment by jonahwilliams** [comment]
You did read that correctly, it was a bit negative! 😉

**Comment by davidd647** [comment]
How frustrating.
