### ISSUE TITLE
Any way to run AnimatedSampler and toImageSync on gpu?

### ISSUE THREAD

**Issue by Spiritcow** [jonahwilliams/flutter_shaders#32]
Hi, @jonahwilliams  I have read all possible issues on github, including yours: https://github.com/flutter/flutter/issues/117786 but I still haven't found a way to make toImageSync work faster on the web. I tried to make a custom engine build and apply a fix from your PR, but for some reason, I end up rendering just a white screen when imageSync goes to the surface GPU. When the implementation with readPixels produces a normal picture. I'm already very close to giving up and just doing it on React, but I would still like to do it on Flutter. Maybe you have some ideas? I just don't understand why you managed to apply this patch and to Image Sync returned a normal picture, but I have a white screen)

**Comment by jonahwilliams** [comment]
You need to be using the canvaskit renderer. Are you using auto and perhaps falling back to html?

**Comment by jonahwilliams** [comment]
Oh I see, you're applying my old patch. (sorry, reading before coffee). I think its likely that patch has long since broken, as the web engine itself is undergoing quite a bit of changes

**Comment by jonahwilliams** [comment]
https://github.com/flutter/engine/pull/47691/files is probably the most up to date, if you haven't tried that already

**Comment by Spiritcow** [comment]
> Owner

Wow, no, this is something new. Will try :) I found some PR's with toGpuImageSync method, but they are also got rollbacked

**Comment by jonahwilliams** [comment]
Closing because I think this issue is ultimately a canvaskit/flutter web problem, there is nothing in this package I can change to make it work
